const S={step:1,layout:'',size:'',finish:'',finishPrice:0,budget:'',timeline:''};
const steps=[...document.querySelectorAll('.step')],bar=document.querySelector('#bar'),counter=document.querySelector('#counter'),empty=document.querySelector('#empty'),lead=document.querySelector('#leadwrap'),overlay=document.querySelector('#overlay'),demo=document.querySelector('#demo');
function step(n){S.step=n;steps.forEach(x=>x.classList.toggle('on',+x.dataset.step===n));bar.style.width=((n-1)/5*100)+'%';counter.textContent='Шаг '+n+' из 5'}
function choose(b){let k=b.dataset.key;document.querySelectorAll('.opt[data-key="'+k+'"]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');S[k]=b.dataset.value;if(k==='finish')S.finishPrice=+(b.dataset.price||0);setTimeout(()=>S.step<5?step(S.step+1):done(),220)}
document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>choose(b));
document.querySelector('#dimNext').onclick=()=>{let a=(document.querySelector('#a').value||'320').replace(/\D/g,'')||'320',b=(document.querySelector('#b').value||'210').replace(/\D/g,'')||'210';S.size=a+' × '+b+' см';step(3)};
function estimate(){let a=+(document.querySelector('#a').value||320),v=190000+(Math.max(220,Math.min(600,a))-220)*360+S.finishPrice;if(S.layout==='Угловая')v+=45000;if(S.layout==='П-образная')v+=100000;if(S.layout==='С островом')v+=145000;let l=Math.round(v/10000)*10,h=Math.round(v*1.18/10000)*10;return '≈ '+l+'–'+h+' тыс. ₽'}
function done(){if(!S.size)S.size='320 × 210 см';bar.style.width='100%';counter.textContent='Готово';overlay.classList.add('on');setTimeout(()=>{document.querySelector('#l1').textContent=S.layout||'Угловая';document.querySelector('#l2').textContent=S.size;document.querySelector('#l3').textContent=S.finish||'Комфорт';document.querySelector('#l4').textContent=S.budget||'250–400 000 ₽';document.querySelector('#l5').textContent=S.timeline||'1–3 месяца';document.querySelector('#l6').textContent=estimate();document.querySelector('#priority').textContent=(S.timeline==='В ближайший месяц'||S.budget==='400–650 000 ₽'||S.budget==='650 000 ₽+')?'Высокий приоритет':'Тёплая заявка';overlay.classList.remove('on');empty.style.display='none';lead.classList.add('show');document.querySelector('#manager').scrollIntoView({behavior:'smooth',block:'center'})},1100)}
function reset(){Object.assign(S,{step:1,layout:'',size:'',finish:'',finishPrice:0,budget:'',timeline:''});document.querySelectorAll('.opt').forEach(x=>x.classList.remove('sel'));document.querySelector('#a').value='320';document.querySelector('#b').value='210';lead.classList.remove('show');empty.style.display='flex';step(1);demo.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#start').onclick=reset;document.querySelector('#managerBtn').onclick=()=>document.querySelector('#compare').scrollIntoView({behavior:'smooth',block:'center'});